import {test,expect} from '@playwright/test';
test('question to live research to answer, on desktop and mobile',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await page.evaluate(async()=>{const image=new Image();image.src='/research-world.png';await image.decode()});
 await expect(page.getByRole('heading',{name:'What are we curious about today?'})).toBeVisible();
 await page.screenshot({path:'docs/new-home-desktop.png',fullPage:true,animations:'disabled'});
 await page.getByLabel('Your research question').fill('What limitations affect retrieval augmented generation?');
 await page.locator('input[type=file]').setInputFiles('tests/fixture.pdf');
 await page.getByRole('button',{name:'Let’s explore'}).click();
 await expect(page.getByLabel('Research progress')).toBeVisible();
 await expect(page.getByRole('heading',{name:'Straight from the source.'})).toBeVisible({timeout:20000});
 await expect(page.locator('.trail-stop.done')).toHaveCount(5);
 await expect(page.locator('.finding')).toContainText(['evaluated']);
 await page.locator('.citations button').first().click();
 await expect(page.getByRole('dialog')).toContainText('An original extracted passage');
 await page.keyboard.press('Escape');
 await page.getByLabel('Follow-up question').fill('What English language limitations are reported?');
 await page.getByRole('button',{name:'Send follow-up'}).click();
 await expect(page.locator('.message.assistant')).toContainText('AI synthesis is not configured');
 await page.screenshot({path:'docs/new-answer-desktop.png',fullPage:true,animations:'disabled'});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'docs/new-answer-mobile.png',fullPage:true,animations:'disabled'});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'ResearchOS home'}).click();
 await page.screenshot({path:'docs/new-home-mobile.png',fullPage:true,animations:'disabled'});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 expect(errors).toEqual([]);
});
